#ifndef _VGA_H
#define _VGA_H

#ifndef SYSTEM_COLORS
#define SYSTEM_COLOR_BLACK					0x00
#define SYSTEM_COLOR_BLUE					0x01
#define SYSTEM_COLOR_GREEN					0x02
#define SYSTEM_COLOR_CYAN					0x03
#define SYSTEM_COLOR_RED					0x04
#define SYSTEM_COLOR_MAGENTA				0x05
#define SYSTEM_COLOR_ORANGE					0x06
#define SYSTEM_COLOR_LT_GRAY				0x07
#define SYSTEM_COLOR_GRAY					0x08
#define SYSTEM_COLOR_LT_BLUE				0x09
#define SYSTEM_COLOR_LT_GREEN				0x0A
#define SYSTEM_COLOR_LT_CYAN				0x0B
#define SYSTEM_COLOR_LT_RED					0x0C
#define SYSTEM_COLOR_LT_MAGENTA				0x0D
#define SYSTEM_COLOR_YELLOW					0x0E
#define SYSTEM_COLOR_WHITE					0x0F
#endif

#endif
